# Generated by Django 4.2.4 on 2023-09-06 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    def create_default_tags(apps, schema_editor):
        Tag = apps.get_model('home', 'Tag')
        Tag.objects.create(id=1, type='Nueva')
        Tag.objects.create(id=2, type='Hogar')
        Tag.objects.create(id=3, type='Trabajo')
        Tag.objects.create(id=4, type='Estudio')
        Tag.objects.create(id=5, type='Deporte')
        

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(default='Nueva', max_length=10)),
            ],
        ),
        migrations.RunPython(create_default_tags),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En progreso', 'En progreso'), ('Completada', 'Completada')], default='Pendiente', max_length=11)),
                ('task_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task_tag', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.tag')),
            ],
        ),
    ]
